### ISSUE TITLE
JSONDecodeError: Expecting property name enclosed in double quotes

### ISSUE THREAD

**Issue by ahbon123** [PKUJohnson/OpenData#7]
```
import pandas as pd
from pyecharts import Bar

def draw_price(city_list, title):
    df_list = []
    for city in city_list:
        df, msg = realestate.get_real_house_price(city)
        if df is not None:
            df_list.append(df)
    
    df = pd.concat(df_list)
    df = df[df['date'] == '201807']
    df.sort_values('price', inplace=True, ascending=True)
    
    axis_x = df['city']
    axis_y = df['price']

    bar = Bar(title, width=600, height=600)
    bar.add("房价", axis_x, axis_y, is_convert=True, is_label_show=True, 
					bar_category_gap='50%', label_pos='right')
    return bar

# 一线城市房价比拼
draw_price(['北京', '上海', '广州', '深圳'], "一线城市房价大比拼")

```
When I run code above, there are following errors, does someone can help me to fix it? Thanks.
```
Traceback (most recent call last):

  File "<ipython-input-51-736af34863f3>", line 25, in <module>
    draw_price(['北京', '上海', '广州', '深圳'], "一线城市房价大比拼")

  File "<ipython-input-51-736af34863f3>", line 7, in draw_price
    df, msg = realestate.get_real_house_price(city)

  File "C:\Users\User\Anaconda3\lib\site-packages\opendatatools\realestate\realestate_interface.py", line 17, in get_real_house_price
    return anjuke_agent.get_real_house_price(city)

  File "C:\Users\User\Anaconda3\lib\site-packages\opendatatools\realestate\anjuke_agent.py", line 56, in get_real_house_price
    xyear = json.loads('{' + AnjukeAgent.extract_word(content, 'xyear:{', '},') + '}')

  File "C:\Users\User\Anaconda3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)

  File "C:\Users\User\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "C:\Users\User\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)

JSONDecodeError: Expecting property name enclosed in double quotes
```

**Comment by PKUJohnson** [comment]
我们运行是可以的
